### ISSUE TITLE
Months as roman numerals

### ISSUE THREAD

**Issue by robin-hutchinson** [ropensci/datefixR#90]
Would it be possible to include dates where the month is given as a roman numeral, please?

E.g. 13/vi/2021 would be 2021-06-13

This format is used in some database systems (https://database.guide/how-to-format-the-month-in-roman-numerals-in-oracle/) and by some biological recorders.

**Comment by nathansam** [comment]
Hi! Sure thing! It should be trivial to implement _in theory_. I will look into it.

**Comment by robin-hutchinson** [comment]
Brilliant thank you! The main issue I found was doing months first (e.g. looking for "April" before the numeral "i"), and then looking for the numerals in an order that the larger numbers were checked first:

"xii", "xi", "ix", "x", "viii", "vii", "vi", "iv", "iii", "ii", "i", "v"

**Comment by nathansam** [comment]
I have added experimental support for months given as Roman numerals to `main`. `roman.numeral = TRUE` must be specified when using either `fix_date_df()` or `fix_date_char()` to add support for roman numerals. This is because there is the possibility of introducing support for Roman numerals breaks some types of dates. Let me know if you run into any issues whilst using it.

**Comment by robin-hutchinson** [comment]
Thanks Nathan, I will use this!
